### ISSUE TITLE
Clubs Page

### ISSUE THREAD

**Issue by Bawanthathilan** [sliit-foss/rsvp-frontend-old#26]

**Comment by sithumonline** [comment]
https://www.sliit.lk/student-life/clubs-societies/

Assing @Binxth

**Comment by Binxth** [comment]
Pull request added
@sithumonline

**Comment by Binxth** [comment]
<img width="1440" alt="Screenshot 2021-03-22 at 12 03 29 PM" src="https://user-images.githubusercontent.com/33088210/111949745-45fa5e00-8b07-11eb-8403-e17d710eaa8a.png">
