### ISSUE TITLE
Fixed Home Page Responsive Issues

### ISSUE THREAD

**Issue by Bawanthathilan** [sliit-foss/rsvp-frontend-old#27]

**Comment by sithumonline** [comment]
Assine @MadhushaPrasad

**Comment by MadhushaPrasad** [comment]
okay I will assign this issue

**Comment by Bawanthathilan** [comment]
updates?

**Comment by MadhushaPrasad** [comment]
Not yet,i will do it immediately

**Comment by LayanJay** [comment]
I have already did some changes to fix the issue. Is it okay to open a pull request regarding this issue?

**Comment by sithumonline** [comment]
> I have already did some changes to fix the issue. Is it okay to open a pull request regarding this issue?

Totally
