### ISSUE TITLE
Login & Registration Page

### ISSUE THREAD

**Issue by Bawanthathilan** [sliit-foss/rsvp-frontend-old#28]
- [ ] Google Login with Firebase Auth

**Comment by sithumonline** [comment]
Need to add two buttons for login and registration.

~~Assign  @di-nethra~~

**Comment by Bawanthathilan** [comment]
## Design (ignore the right side illustrations)
![image](https://user-images.githubusercontent.com/38850236/119532511-93fb3e80-bda2-11eb-8e90-9597fc16a699.png)

**Comment by MadhushaPrasad** [comment]
done
